### PR TITLE
Add SETTITLE command to set window title

### PR DESCRIPTION
**Pull request by jakobkukla**
Add support for the SETTITLE command to set the window title. rofi has a `-window-title` option to do exactly this.

See [rofi-dmenu.5](https://davatorium.github.io/rofi/current/rofi-dmenu.5/) and `info pinentry`

### CODE REVIEW

**Comment by plattfot** [comment]
Hi,
thank you the feature, it's looking good. I'm missing a copyright notice at the top of the file.  Would you mind adding one? See [reuse.software/spec-3.0](https://reuse.software/spec-3.0/#format-of-copyright-notices).

Thanks

**Comment by jakobkukla** [comment]
Hi :) Like that? Should I add myself to AUTHORS as well?

**Comment by plattfot** [comment]
Good point, I forgot about the AUTHORS file. If you want then please otherwise I can just add you after I've merged this.

**Comment by jakobkukla** [comment]
Just add me afterwards! Thanks!

**Pull request merged**
